### ISSUE TITLE
Lunch?

### ISSUE THREAD

**Issue by jschrier** [mfbliposome/opentrons#1]
What should we order for lunch during today's hackathon?

**Comment by ewroginek** [comment]
The Thai food sounds like a good idea

**Comment by ekosso** [comment]
Mexican food?

**Comment by jschrier** [comment]
https://www.grubhub.com/restaurant/mae-kong-thai-restaurant-26-main-st-new-britain/2434389

I will create a new file called `lunch.md` that everyone can edit with their order
